openshift/template.yaml
=> Reduce CPU allocation and limit

openshift/template.yaml
=> Change service namespace from bayesian to f8a

openshift/template.yaml
=> Change deployment name to match the one given to SaaSherder

recommendation_engine/flask_predict.py, swagger.yaml
=> Change API request to match the request coming from backbone

openshift/template.yaml
=> Change memory requirement to match sanction request for prod

README.md
=> Change citation formatting

openshift/template.yaml
=> Increase memory request to prevent pod from crashing on staging

openshift/template.yaml
=> Increase memory request to gague usage

docker-compose.yml
=> Change image name in docker compose

Dockerfile, Dockerfile.tests
=> Change Dockerfile to use Python 3.4

Dockerfile.rhel, Makefile, cico_setup.sh
Depends on https://github.com/openshiftio/openshiftio-cico-jobs/pull/638 to be merged first.
=> Move to RHEL

tests/scripts/entrypoint-test.sh
Problem description: https://github.com/openshiftio/openshift.io/issues/3750
=> Code coverage threshold check

requirements.in, requirements.txt
=> Upgrade flask to latest version

recommendation_engine/flask_predict.py
=> Make debug port same as docker-compose and openshift

openshift/template.yaml
=> Fix template by adding env property

docker-compose.yml, openshift/template.yaml, recommendation_engine/config/params_scoring.py, recommendation_engine/predictor/online_recommendation.py
=> Update scoring to use a minimum confidence score of 30%

docker-compose.yml, openshift/template.yaml, recommendation_engine/config/params_scoring.py, recommendation_engine/data_store/s3_data_store.py
=> Fix minimum confidence threshold

Dockerfile, cico_run_pydoc.sh, cico_run_pylint.sh, requirements.txt
=> Upgrade version of Jinja

openshift/template.yaml
A previous commit introduced an invalid yaml.
Please delete options that are not relevant.
=> fix invalid yaml

docker-compose.yml, openshift/template.yaml, recommendation_engine/config/cloud_constants.py
Changed the AWS bucket name variable in docker-compose.yml and in cloud constants according to new AWS changes.
=> Change variable names in cloud constants and in compose.yml

training/datastore/s3_connection.py
Updated the path for Node data dump, and updated the bucket structure respectively
=> Update the path for fetching data dump from S3

recommendation_engine/predictor/online_recommendation.py
Added logging for knowing models paths and package id maps paths.
=> Add logging for model paths and package maps

recommendation_engine/predictor/online_recommendation.py
Added s3 bucket path also for debugging
=> Add s3 bucket path

openshift/template.yaml
Updated the secret access key in openshift template
=> Update the secret access key in template

Dockerfile.tests, recommendation_engine/utils/fileutils.py, training/datastore/s3_connection.py
As E2E is failing again because of changed data path
=> Update data path, dockerfile and code

MAINTAINERS
Add lsuman@redhat.com as the first maintainer of this repository.
=> Update list of maintainers

training/datastore/preprocess_data.py
Earlier, it was picking up the data from different variable('package_list'), which is updated now.
=> Update the variable name from raw data will be picked.

training/datastore/get_keywords.py, training/datastore/preprocess_data.py, training/datastore/s3_connection.py
As part of NPM retraining pipeline resource optimisation task, we have moved data loading and processing out of EMR job. 
This PR ignores the data loading and NPM package update in the flow, instead it uses pre-processed file stored in S3.
Changes follows the cost optmization proposal made under :: [Retraining Pipeline Resource Optimization](https://docs.google.com/document/d/1OFBQDWiGGEb045eTJfNCxz9G4n1jYvH9h3AHe9pXCPc/edit?usp=sharing)
Fixes # (issue)
https://issues.redhat.com/browse/APPAI-1781
Please delete options that are not relevant.
=> [APPAI-1781] Using pre-processed data for model generation
